<a href="https://colab.research.google.com/github/guimatech/data-structure-and-algorithm/blob/main/Deque.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Deque

In [1]:
import numpy as np

In [2]:
class Deque:

  def __init__(self, capacidade):
    self.capacidade = capacidade
    self.inicio = -1
    self.final = 0
    self.numero_elementos = 0
    self.valores = np.empty(self.capacidade, dtype=int)

  def __deque_cheio(self):
    return (self.inicio == 0 and self.final == self.capacidade - 1) or (self.inicio == self.final + 1)

  def __deque_vazio(self):
    return self.inicio == -1

  def insere_inicio(self, valor):
    if self.__deque_cheio():
      print('O deque está cheio')
      return

    # Se estiver vazio
    if self.inicio == -1:
      self.inicio = 0
      self.final = 0
    # Início estiver na primeira posição
    elif self.inicio == 0:
      self.inicio = self.capacidade - 1
    else:
      self.inicio -= 1

    self.valores[self.inicio] = valor

  def insere_final(self, valor):
    if self.__deque_cheio():
      print('O deque está cheio')
      return

    # Se estiver vazio
    if self.inicio == -1:
      self.inicio = 0
      self.final = 0
    # Final estiver na última posição
    elif self.final == self.capacidade - 1:
      self.final = 0
    else:
      self.final += 1

    self.valores[self.final] = valor

  def excluir_inicio(self):
    if self.__deque_vazio():
      print('O deque já está vazio')
      return

    # Possui somente um elemento
    if self.inicio == self.final:
      self.inicio = -1
      self.final = -1
    else:
      # Volta para a posição inicial
      if self.inicio == self.capacidade - 1:
        self.inicio = 0
      else:
        # Incrementar início para remover o início atual
        self.inicio += 1

  def excluir_final(self):
    if self.__deque_vazio():
      print('O deque já está vazio')
      return

    if self.inicio == self.final:
      self.inicio = -1
      self.final = -1
    elif self.inicio == 0:
      self.final = self.capacidade - 1
    else:
      self.final -= 1

  def get_inicio(self):
    if self.__deque_vazio():
      print('O deque já está vazio')
      return

    return self.valores[self.inicio]

  def get_final(self):
    if self.__deque_vazio() or self.final < 0:
      print('O deque já está vazio')
      return

    return self.valores[self.final]

In [3]:
deque = Deque(5)

In [4]:
deque.insere_final(5)

In [5]:
deque.get_inicio(), deque.get_final()

(5, 5)

In [6]:
# 5 10
deque.insere_final(10)

In [7]:
deque.get_inicio(), deque.get_final()

(5, 10)

In [8]:
# 3 5 10
deque.insere_inicio(3)

In [9]:
deque.get_inicio(), deque.get_final()

(3, 10)

In [10]:
# 2 3 5 10 11
deque.insere_inicio(2)
deque.insere_final(11)

In [11]:
deque.get_inicio(), deque.get_final()

(2, 11)

In [12]:
# 3 5 10
deque.excluir_inicio()
deque.excluir_final()

In [13]:
deque.get_inicio(), deque.get_final()

(3, 10)

In [14]:
deque.valores

array([ 5, 10, 11,  2,  3])

In [15]:
deque.inicio

4

In [16]:
deque.final

1

In [17]:
a = np.array([[1,2],[3,4]])
b = np.array([[4,5], [8,9]])

In [18]:
a.dot(b)

array([[20, 23],
       [44, 51]])

In [19]:
b.dot(a)

array([[19, 28],
       [35, 52]])